config/routes.rb
Proj::Application.routes.draw do
  get "albums/new"
  match 'pictures/addtags' => 'pictures#addtags', :as => :addtags_picture
  get "categories/new"
  get "pictures/new"
  get "pictures/allpict"
  get "pictures/test"
  resources :categories
  resources :albums
  resources :pictures 
  resources :pictures do
    member do
      get :tag
      get :abc
      get :allpict
      get :show 
    end
  end
  

   root :to => 'pictures#new'

end

app/models/album.rb
class Album < ActiveRecord::Base
 attr_accessible :name
 has_many :pictures
end

app/models/category.rb
class Category < ActiveRecord::Base
 attr_accessible :name

 has_many :pictures
end

app/models/picture.rb
require "open-uri"

class Picture < ActiveRecord::Base
 attr_accessible :name, :picture, :category_id

 has_many :tagging
 has_many :tag, :through => :tagging
 
 belongs_to :category
 belongs_to :album
 has_attached_file :picture, :styles => {  :thumb => "100x100>" }
 default_scope :order => 'pictures.created_at DESC'
 
  def picture_from_url(url)
    self.picture = open(url)
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  validates :name, :uniqueness =>true
  has_many :tagging
  has_many :picture, :through => :tagging
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
 attr_accessible :tag_id, :taggeble_id 

 belongs_to :picture
 belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new

  end
  
  def show
   @album=Album.find(params[:id])
   @pictures=@album.pictures
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  end
   
  def show
  end

  def update
  @category=Category.find(params[:category_id])
  redirect_to '/pictures/allpict'
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
  @picture=Picture.new
  end

  def create
   @album=Album.new
   i=0
   params[:picture][:picture].each do
    @picture=@album.pictures.new()
    @picture.name=params[:picture][:name]
    @picture.picture=params[:picture][:picture][i]
    @picture.category_id=(params[:picture][:category_id])
    @picture.save
    i=i+1
    end
   @album.save
  redirect_to @album
  end
  
  def show
    @picture = Picture.find(params[:id])
    @picture_tags=Tagging.where(picture_id:@picture.id)
  end
  
  def allpict
   @tagall=Tag.all
   if params[:id]!=nil
    @category=Category.find(params[:id])
    @pictures=@category.pictures.paginate(:page => params[:page], :per_page => 24)
   else
    @pictures = Picture.paginate(:page => params[:page], :per_page => 24)
   end
  end
  
  def addtags
   @picture=Picture.find_by_id(params[:id])
   tagging=Tagging.new
   i=Tag.find_by_name(params[:tag])
    if !i
     tag=Tag.new()
     tag.name=params[:tag]
     tag.save
     tagging.tag_id=tag.id
     tagging.picture_id=@picture.id
     tagging.save
    else if !Tagging.find_by_tag_id_and_picture_id(i.id,@picture.id)
              tagging.tag_id=i.id
              tagging.picture_id=@picture.id
              tagging.save
         end
    end
   redirect_to @picture
  end

  def tag
   #a=params[:id]
   #@pictures=Picture.where(id: Tagging.find_all_by_tag_id(a).map{|u| u.picture_id})
   @pictures=Tag.find_by_id(params[:id]).picture
  end
  
  def abc
   @picture = Picture.find(params[:id])
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/albums/new.html.erb
<h1>Albums#new</h1>
<p>Find me in app/views/albums/new.html.erb</p>

app/views/albums/show.html.erb
<% @pictures.each do |pictures| %>
      <%= image_tag pictures.picture.url(:thumb) %></br>
      <hr>
  <% end %>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proj</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/abc.html.erb
<%= image_tag @picture.picture.url(:original) %>

app/views/pictures/allpict.html.erb
Все изображения<a href="http://localhost:3000/pictures/allpict">>></a></br>
<%Category.all.each do |category|%>
<%=category.name%><%=link_to ">>",allpict_picture_path(category) %></br>
<%end%>
<%@tagall.each do |tag|%>
<%=link_to tag.name,{ :action => :tag, :id => tag.id }%>
<%end%>
<%=will_paginate%>
 <table width="100%" >
 
 <%i=0%>
 <% @pictures.each do |picture| %>
    <%if i<6%>
     <td><%=picture.name%><%= link_to ">>", picture %></br><%i=i+1%>
       <%= image_tag picture.picture.url(:thumb)%></td>
   <%else%>
   <tr></tr><td><%= link_to picture.name, picture %></br>
       <%= image_tag picture.picture.url(:thumb)%></td><%i=1%>
   <%end%>
   <% end %>
</table>

app/views/pictures/new.html.erb
<h2>Загрузка картинки</h2>
<%= form_for @picture,
             :html => { :multipart => true } do |form| %>
    <%= form.label :Название %><br />
    <%= form.text_field :name %></br>
    <%=form.file_field :picture, :multiple => true %> 

<%=form.select :category_id, "<option value="">Выбор категории</option>".html_safe + options_from_collection_for_select(Category.all, :id, :name)%></br>   
  <%= form.submit "Загрузить" %>
<% end %>
Все изображения<a href="http://localhost:3000/pictures/allpict">>></a></br>

app/views/pictures/show.html.erb
все таги 
<%@picture_tags.each do |picture_tags|%>
<%=picture_tags.tag.name%>
<%end%>
<%= @picture.name%></br>
<%= image_tag @picture.picture.url(:thumb) %></br>
<%=link_to "оригинальный размер", abc_picture_path(@picture)%></br>
<a href="http://localhost:3000/pictures/allpict">Все Изображения</a></br>
Добавить таги
<%= form_tag(addtags_picture_path) do %>
<%= text_field_tag :tag %>
<%= text_field_tag :id, @picture.id%>
<%= submit_tag "Сохранить" %>
<% end %>

app/views/pictures/tag.html.erb
<table width="100%" >
 
 <%i=0%>
 <% @pictures.each do |picture| %>
    <%if i<6%>
     <td><%=picture.name%><%= link_to ">>", picture %></br><%i=i+1%>
       <%= image_tag picture.picture.url(:thumb)%></td>
   <%else%>
   <tr></tr><td><%= link_to picture.name, picture %></br>
       <%= image_tag picture.picture.url(:thumb)%></td><%i=1%>
   <%end%>
   <% end %>
</table>